#!/bin/bash

# See https://developer.apple.com/library/archive/technotes/tn2339/_index.html



ARCH=`uname -m`

ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PRJ="${ROOT}/macos"

export ONLY_ACTIVE_ARCH=YES

export BUILD_KIND="Debug"

declare -a projects=( "RustDspInProcessDemo" "RustDspPlainDemo" )

for project in "${projects[@]}"
do
    PRJDIR="${PRJ}/${project}"
    echo "******************************** Clean ${project} ********************************"
    rm -Rf "${PRJDIR}/DerivedData"
done

for project in "${projects[@]}"
do
    echo "******************************** Find/build subframeworks in ${project} ********************************"
    PRJDIR="${PRJ}/${project}"
    cd "${PRJDIR}"
    TARGET=`xcodebuild -list 2>/dev/null | grep UI | uniq | xargs`
    if [ ! -z "${TARGET}" ]; then
        echo "GOT ${TARGET} in ${project}"
        ARCHS=`uname -m` xcodebuild build -arch `uname -m` -configuration "${BUILD_KIND}" -scheme "${TARGET}" \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration -workspace "${PRJDIR}/${project}.xcodeproj/project.xcworkspace"
    fi
    cd "${ROOT}"
done

set -e

for project in "${projects[@]}"
do
    PRJDIR="${PRJ}/${project}"
    echo
    echo
    echo "******************************** Build ${project} ********************************"
    rm -Rf "${PRJDIR}/DerivedData"
    echo "Running xcodebuild build ${WS_BUILD_ARGS} in ${PRJDIR}"
    cd "${PRJDIR}"

    ARCHS=`uname -m` xcodebuild build -arch `uname -m` -configuration "${BUILD_KIND}" -scheme "${project}Extension" -allowProvisioningUpdates \
        -allowProvisioningDeviceRegistration -workspace "${PRJDIR}/${project}.xcodeproj/project.xcworkspace"
    ARCHS=`uname -m` xcodebuild build -arch `uname -m` -configuration "${BUILD_KIND}" -scheme "${project}" -allowProvisioningUpdates \
        -allowProvisioningDeviceRegistration -workspace "${PRJDIR}/${project}.xcodeproj/project.xcworkspace"
    
    cd "${ROOT}"
done
