#!/bin/bash

ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "${ROOT}"

# Clean all build products
cargo clean

# Delete the built and cached cbindgen-bindgen from bin/
rm -Rf "${ROOT}/bin"

# Delete all old build products
rm -Rf macos/libs/ macos/xcframeworks/ macos/swift/ macos/headers/ target/universal-*

# Wipe build directories for all audio unit Xcode projects
find ./macos/ -iname DerivedData | xargs rm -Rf

